/**:
  ros__parameters:
    min_longitudinal_offset: 1.8
    max_longitudinal_offset: 2.1
    min_lateral_offset: 0.7
    max_lateral_offset: 0.95
    min_height_offset: 0.9
    max_height_offset: 1.15