/**:
  ros__parameters:
    wheel_radius: 0.35 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.2 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 2.75 # between front wheel center and rear wheel center
    wheel_tread: 1.7 # between left wheel center and right wheel center
    front_overhang: 0.65 # between front wheel center and vehicle front
    rear_overhang: 0.9 # between rear wheel center and vehicle rear
    left_overhang: 0.35 # between left wheel center and vehicle left
    right_overhang: 0.35 # between right wheel center and vehicle right
    vehicle_height: 1.5
    max_steer_angle: 0.70 # [rad]

# ************************************************************************************
# whell_radius: タイヤの半径
# wheel_width: タイヤの横幅
# wheel_base: 前輪と後輪の距離
# wheel_tread: 左と右のタイヤの距離 track_widthと同じ
# front_overhang: 前輪と車体の一番前に位置する物体との距離
# rear_overhang: 後輪と車体の一番後ろに位置する物体との距離
# left_overhang: 左タイヤと車体の一番左に位置する物体との距離
# righ_overhang: 右タイヤと車体の一番右に位置する物体との距離
# vehicle_height: 車両の高さ
# max_steer_angle: 最大ステアリング角度
# https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-interfaces/components/vehicle-dimensions/
# ************************************************************************************